/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendorSettingsRouteImport } from './routes/_app/vendor/settings'
import { Route as AppVendorNotificationsRouteImport } from './routes/_app/vendor/notifications'
import { Route as AppVendorDocumentsRouteImport } from './routes/_app/vendor/documents'
import { Route as AppVendorDashboardRouteImport } from './routes/_app/vendor/dashboard'
import { Route as AppClientSettingsRouteImport } from './routes/_app/client/settings'
import { Route as AppClientNotificationsRouteImport } from './routes/_app/client/notifications'
import { Route as AppClientDocumentsRouteImport } from './routes/_app/client/documents'
import { Route as AppClientDashboardRouteImport } from './routes/_app/client/dashboard'
import { Route as AppVendorProjectsIndexRouteImport } from './routes/_app/vendor/projects/index'
import { Route as AppClientProjectsIndexRouteImport } from './routes/_app/client/projects/index'
import { Route as AppVendorProjectsProjectIdRouteImport } from './routes/_app/vendor/projects/$projectId'
import { Route as AppClientProjectsProjectIdRouteImport } from './routes/_app/client/projects/$projectId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorSettingsRoute = AppVendorSettingsRouteImport.update({
  id: '/vendor/settings',
  path: '/vendor/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorNotificationsRoute = AppVendorNotificationsRouteImport.update({
  id: '/vendor/notifications',
  path: '/vendor/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorDocumentsRoute = AppVendorDocumentsRouteImport.update({
  id: '/vendor/documents',
  path: '/vendor/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorDashboardRoute = AppVendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientSettingsRoute = AppClientSettingsRouteImport.update({
  id: '/client/settings',
  path: '/client/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppClientNotificationsRoute = AppClientNotificationsRouteImport.update({
  id: '/client/notifications',
  path: '/client/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppClientDocumentsRoute = AppClientDocumentsRouteImport.update({
  id: '/client/documents',
  path: '/client/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppClientDashboardRoute = AppClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorProjectsIndexRoute = AppVendorProjectsIndexRouteImport.update({
  id: '/vendor/projects/',
  path: '/vendor/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientProjectsIndexRoute = AppClientProjectsIndexRouteImport.update({
  id: '/client/projects/',
  path: '/client/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorProjectsProjectIdRoute =
  AppVendorProjectsProjectIdRouteImport.update({
    id: '/vendor/projects/$projectId',
    path: '/vendor/projects/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientProjectsProjectIdRoute =
  AppClientProjectsProjectIdRouteImport.update({
    id: '/client/projects/$projectId',
    path: '/client/projects/$projectId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/client/dashboard': typeof AppClientDashboardRoute
  '/client/documents': typeof AppClientDocumentsRoute
  '/client/notifications': typeof AppClientNotificationsRoute
  '/client/settings': typeof AppClientSettingsRoute
  '/vendor/dashboard': typeof AppVendorDashboardRoute
  '/vendor/documents': typeof AppVendorDocumentsRoute
  '/vendor/notifications': typeof AppVendorNotificationsRoute
  '/vendor/settings': typeof AppVendorSettingsRoute
  '/client/projects/$projectId': typeof AppClientProjectsProjectIdRoute
  '/vendor/projects/$projectId': typeof AppVendorProjectsProjectIdRoute
  '/client/projects/': typeof AppClientProjectsIndexRoute
  '/vendor/projects/': typeof AppVendorProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/client/dashboard': typeof AppClientDashboardRoute
  '/client/documents': typeof AppClientDocumentsRoute
  '/client/notifications': typeof AppClientNotificationsRoute
  '/client/settings': typeof AppClientSettingsRoute
  '/vendor/dashboard': typeof AppVendorDashboardRoute
  '/vendor/documents': typeof AppVendorDocumentsRoute
  '/vendor/notifications': typeof AppVendorNotificationsRoute
  '/vendor/settings': typeof AppVendorSettingsRoute
  '/client/projects/$projectId': typeof AppClientProjectsProjectIdRoute
  '/vendor/projects/$projectId': typeof AppVendorProjectsProjectIdRoute
  '/client/projects': typeof AppClientProjectsIndexRoute
  '/vendor/projects': typeof AppVendorProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/client/dashboard': typeof AppClientDashboardRoute
  '/_app/client/documents': typeof AppClientDocumentsRoute
  '/_app/client/notifications': typeof AppClientNotificationsRoute
  '/_app/client/settings': typeof AppClientSettingsRoute
  '/_app/vendor/dashboard': typeof AppVendorDashboardRoute
  '/_app/vendor/documents': typeof AppVendorDocumentsRoute
  '/_app/vendor/notifications': typeof AppVendorNotificationsRoute
  '/_app/vendor/settings': typeof AppVendorSettingsRoute
  '/_app/client/projects/$projectId': typeof AppClientProjectsProjectIdRoute
  '/_app/vendor/projects/$projectId': typeof AppVendorProjectsProjectIdRoute
  '/_app/client/projects/': typeof AppClientProjectsIndexRoute
  '/_app/vendor/projects/': typeof AppVendorProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/client/dashboard'
    | '/client/documents'
    | '/client/notifications'
    | '/client/settings'
    | '/vendor/dashboard'
    | '/vendor/documents'
    | '/vendor/notifications'
    | '/vendor/settings'
    | '/client/projects/$projectId'
    | '/vendor/projects/$projectId'
    | '/client/projects/'
    | '/vendor/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/client/dashboard'
    | '/client/documents'
    | '/client/notifications'
    | '/client/settings'
    | '/vendor/dashboard'
    | '/vendor/documents'
    | '/vendor/notifications'
    | '/vendor/settings'
    | '/client/projects/$projectId'
    | '/vendor/projects/$projectId'
    | '/client/projects'
    | '/vendor/projects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/client/dashboard'
    | '/_app/client/documents'
    | '/_app/client/notifications'
    | '/_app/client/settings'
    | '/_app/vendor/dashboard'
    | '/_app/vendor/documents'
    | '/_app/vendor/notifications'
    | '/_app/vendor/settings'
    | '/_app/client/projects/$projectId'
    | '/_app/vendor/projects/$projectId'
    | '/_app/client/projects/'
    | '/_app/vendor/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendor/settings': {
      id: '/_app/vendor/settings'
      path: '/vendor/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof AppVendorSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/notifications': {
      id: '/_app/vendor/notifications'
      path: '/vendor/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof AppVendorNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/documents': {
      id: '/_app/vendor/documents'
      path: '/vendor/documents'
      fullPath: '/vendor/documents'
      preLoaderRoute: typeof AppVendorDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/dashboard': {
      id: '/_app/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof AppVendorDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client/settings': {
      id: '/_app/client/settings'
      path: '/client/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof AppClientSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client/notifications': {
      id: '/_app/client/notifications'
      path: '/client/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof AppClientNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client/documents': {
      id: '/_app/client/documents'
      path: '/client/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof AppClientDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client/dashboard': {
      id: '/_app/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof AppClientDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/projects/': {
      id: '/_app/vendor/projects/'
      path: '/vendor/projects'
      fullPath: '/vendor/projects/'
      preLoaderRoute: typeof AppVendorProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client/projects/': {
      id: '/_app/client/projects/'
      path: '/client/projects'
      fullPath: '/client/projects/'
      preLoaderRoute: typeof AppClientProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/projects/$projectId': {
      id: '/_app/vendor/projects/$projectId'
      path: '/vendor/projects/$projectId'
      fullPath: '/vendor/projects/$projectId'
      preLoaderRoute: typeof AppVendorProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client/projects/$projectId': {
      id: '/_app/client/projects/$projectId'
      path: '/client/projects/$projectId'
      fullPath: '/client/projects/$projectId'
      preLoaderRoute: typeof AppClientProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientDashboardRoute: typeof AppClientDashboardRoute
  AppClientDocumentsRoute: typeof AppClientDocumentsRoute
  AppClientNotificationsRoute: typeof AppClientNotificationsRoute
  AppClientSettingsRoute: typeof AppClientSettingsRoute
  AppVendorDashboardRoute: typeof AppVendorDashboardRoute
  AppVendorDocumentsRoute: typeof AppVendorDocumentsRoute
  AppVendorNotificationsRoute: typeof AppVendorNotificationsRoute
  AppVendorSettingsRoute: typeof AppVendorSettingsRoute
  AppClientProjectsProjectIdRoute: typeof AppClientProjectsProjectIdRoute
  AppVendorProjectsProjectIdRoute: typeof AppVendorProjectsProjectIdRoute
  AppClientProjectsIndexRoute: typeof AppClientProjectsIndexRoute
  AppVendorProjectsIndexRoute: typeof AppVendorProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientDashboardRoute: AppClientDashboardRoute,
  AppClientDocumentsRoute: AppClientDocumentsRoute,
  AppClientNotificationsRoute: AppClientNotificationsRoute,
  AppClientSettingsRoute: AppClientSettingsRoute,
  AppVendorDashboardRoute: AppVendorDashboardRoute,
  AppVendorDocumentsRoute: AppVendorDocumentsRoute,
  AppVendorNotificationsRoute: AppVendorNotificationsRoute,
  AppVendorSettingsRoute: AppVendorSettingsRoute,
  AppClientProjectsProjectIdRoute: AppClientProjectsProjectIdRoute,
  AppVendorProjectsProjectIdRoute: AppVendorProjectsProjectIdRoute,
  AppClientProjectsIndexRoute: AppClientProjectsIndexRoute,
  AppVendorProjectsIndexRoute: AppVendorProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
